apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: slapd

resources:
  - deployment/slapd.yaml
  - deployment/client.yaml
  - service.yaml

configMapGenerator:
  - name: slapd-config
    files:
      - config/00-mkdirs.sh
      - config/05-config.ldif
