apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: slapd
          image: ghcr.io/larsks/docker-slapd-example:main
          command:
            - sleep
            - inf
